// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'key',
    appId: 'appid',
    messagingSenderId: 'senderid',
    projectId: 'flutter_ecommerce_app',
    authDomain: 'flutter_ecommerce_app.firebaseapp.com',
    storageBucket: 'flutter_ecommerce_app.firebasestorage.app',
    measurementId: 'measurementId',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'apikey',
    appId: 'appid',
    messagingSenderId: 'sendid',
    projectId: 'flutter_ecommerce_app',
    storageBucket: 'flutter_ecommerce_app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'key',
    appId: 'apid',
    messagingSenderId: 'senderid',
    projectId: 'flutter_ecommerce_app',
    storageBucket: 'flutter_ecommerce_app.firebasestorage.app',
    iosBundleId: 'com.example.flutter_ecommerce_app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'key',
    appId: 'apid',
    messagingSenderId: 'senderid',
    projectId: 'flutter_ecommerce_app',
    storageBucket: 'flutter_ecommerce_app.firebasestorage.app',
    iosBundleId: 'com.example.flutter_ecommerce_app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'key',
    appId: 'appid',
    messagingSenderId: 'senderid',
    projectId: 'flutter_ecommerce_app',
    authDomain: 'flutter_ecommerce_app.firebaseapp.com',
    storageBucket: 'flutter_ecommerce_app.firebasestorage.app',
    measurementId: 'measurementid',
  );
}
